Browser("Dev REP forms").Page("Dev REP forms").Link("Product Information Template").Click @@ hightlight id_;_Browser("Dev REP forms").Page("Dev REP forms").Link("Product Information Template")_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebEdit("company_id_3").Set "12345" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebEdit("company id 3")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebEdit("dossier_id_3").Set "1a2b3c4" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebEdit("dossier id 3")_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebList("dossier_type_3").Select "Biologic" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebList("dossier type 3")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebEdit("prod_name_3").Set "H20" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebEdit("prod name 3")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebEdit("proper_name_3").Set "WATER" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebEdit("proper name 3")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebElement("Manufacturer/Sponsor").Click @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebElement("Manufacturer/Sponsor")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebCheckBox("manuid").Set "ON" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebCheckBox("manuid")_;_script infofile_;_ZIP::ssf8.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebCheckBox("thisActivity").Set "ON" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebCheckBox("thisActivity")_;_script infofile_;_ZIP::ssf9.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebCheckBox("maillingid").Set "ON" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebCheckBox("maillingid")_;_script infofile_;_ZIP::ssf10.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebButton("Add Importer").Click @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebButton("Add Importer")_;_script infofile_;_ZIP::ssf11.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebEdit("importerid_919").Set "12345" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebEdit("importerid 919")_;_script infofile_;_ZIP::ssf12.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebEdit("importer_company_name_919").Set "Compu-Global-Hyper-Mega-Net" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebEdit("importer company name 919")_;_script infofile_;_ZIP::ssf13.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebEdit("STREET_919").Set "123 Fake Street" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebEdit("STREET 919")_;_script infofile_;_ZIP::ssf14.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebEdit("CITY_919").Set "Springfield" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebEdit("CITY 919")_;_script infofile_;_ZIP::ssf15.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebList("province_919").Select "Manitoba" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebList("province 919")_;_script infofile_;_ZIP::ssf16.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebEdit("postal_919").Set "A1B 2C3" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebEdit("postal 919")_;_script infofile_;_ZIP::ssf17.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebButton("Save Record").Click @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebButton("Save Record")_;_script infofile_;_ZIP::ssf18.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebList("drug_use_3").Select "Human" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebList("drug use 3")_;_script infofile_;_ZIP::ssf19.xml_;_
Browser("Dev REP forms").Page("Product Information Template:").WebCheckBox("isPrescriptionDrugList").Set "ON" @@ hightlight id_;_Browser("Dev REP forms").Page("Product Information Template:").WebCheckBox("isPrescriptionDrugList")_;_script infofile_;_ZIP::ssf20.xml_;_
